[package]
name = "verified_ranges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bit_field = "0.7.0"
# zerocopy = "0.5.0"
derive_more = "0.99.0"
prusti-contracts = "^0.1"